### ISSUE TITLE
Support socket activation

### ISSUE THREAD

**Issue by galgalesh** [brailcom/speechd#336]
It would be really useful to have Socket activation support so that speechd gets launched automatically when a client connects to the socket.

See https://github.com/brailcom/speechd/issues/335#issuecomment-625007201 for more context.

**Comment by jhenstridge** [comment]
For anyone who wants to try and implement this, the main parts would be:

1. Install a `speech-dispatcher.socket` file to `/usr/lib/systemd/user`.  It should use `%t/speech-dispatcher/speechd.sock` as its `ListenStream` value, and be `WantedBy` `sockets.target`
2. Install a `speech-dispatcher.service` file to the same directory, similar to the existing system service, but with `Requires=speech-dispatcher.socket`.
3. Link speech-dispatcher to libsystemd, and call `sd_listen_fds()` to check whether we're launched via socket activation.  If it returns >= 1, then use `SD_LISTEN_FDS_START` as `server_socket` rather than creating and binding a new socket.

It's probably also worth not running speech-dispatcher with `-d` in the systemd unit, so it can be treated like a `Type=simple` daemon.  This makes it easier for systemd to track the daemon process.

**Comment by sthibaul** [comment]
> sounds to me like a dupe of https://github.com/brailcom/speechd/issues/336

indeed, anybody working on the support should take into account the comments from both reports :)
