### ISSUE TITLE
Speaking certain characters with sd_voxin makes speech-dispatcher unresponsive

### ISSUE THREAD

**Issue by joanmarie** [brailcom/speechd#857]
### Step to reproduce

1. In a terminal, enter the following:

```
$ spd-say -c -o espeak-ng "<"
$ spd-say -c -o espeak-ng "<"
$ spd-say -c -o voxin "<"
$ spd-say -c -o voxin "<"
```

### Obtained behavior

With espeak-ng, the character is spoken each time and `spd-say` exits. With voxin, nothing is heard after the first attempt, but `spd-say` exits. With the second attempt, nothing is heard *and* `spd-say` does not exit. The `sd_voxin` process's CPU usage spikes to 100%. (Are there debugging symbols we can get our hands on? Output from `gdb` was useless.)

### Expected behavior

The character would always be spoken, but failing that, `spd-say` wouldn't hang.

### Environment, logs, etc.

* The contents of my `voxin.log` is just a single line: `Error opening configuration file '/etc/speech-dispatcher/modules/voxin.conf'`. But voxin works fine (modulo this particular bug). For instance if I replace "<" with "h", the bug does not occur. 
* [speech-dispatcher.log](https://github.com/brailcom/speechd/files/12782020/speech-dispatcher.log)
* Fedora 39, speech-dispatcher-0.11.5-1.fc39.x86_64
* Voxin 3.3rc5 (Guess I should check if there's an update...)

**Comment by sthibaul** [comment]
Since `sd_voxin` comes from the Voxin package, that'd rather have to be discussed with the Voxin authors?

**Comment by sthibaul** [comment]
Note: to get more logs, you can put
```
Debug 1
```

in `/etc/speech-dispatcher/modules/voxin.conf`

**Comment by sthibaul** [comment]
What I can see in the logs is in that in both `<` and `>` cases, `&lt;` and `&gt;` are sent to the synth. Only the former case seems to be posing problem, speech-dispatcher's `ibmtts.c` is stuck in the `eciAddText` call, so it cannot do better here...

**Comment by joanmarie** [comment]
Makes sense, but any guesses as to why it's only a problem now? It was reported on the Orca list, and I'm rather surprised that we're only just now hitting it....

**Comment by joanmarie** [comment]
For completeness, here's the [voxin.log](https://github.com/brailcom/speechd/files/12782451/voxin.log) from 3.3rc6.

**Comment by joanmarie** [comment]
Also for completeness, I just emailed the contact address for Oralux to report this issue. (Couldn't find an issue tracker.) I CCed @sthibaul. :crossed_fingers:

**Comment by sthibaul** [comment]
> Makes sense, but any guesses as to why it's only a problem now?

Some improper parsing of the `&lt;` entity, but I don't have any more precise idea.

> It was reported on the Orca list, and I'm rather surprised that we're only just now hitting it....

It depends on the actual configuration. Actually in my setup I had to disable the `symbols.dic` processing, which was replacing it with an actual word.

**Comment by sthibaul** [comment]
Ah, in your setup it's actually a mere `<` that is sent to the synth. But that's the same behavior as I observe.

**Comment by jeremyp3** [comment]
for your information, I had already reported this problem to @gcasse 

I received a patch from him to correct the voxin crash.

**Comment by joanmarie** [comment]
> for your information, I had already reported this problem to @gcasse
> 
> I received a patch from him to correct the voxin crash.

Good to know there's already a fix. Now we need it in a release.

**Comment by jeremyp3** [comment]
@joanmarie I edited my comment to include the patch link, if that helps.

**Comment by tgrushka** [comment]
Hi guys, speech-dispatcher is still crashing for me with `libvoxin.so.1.6.3` and IBM TTS "eloquence" voice (american_english,en,US) when speaking text that includes a newline and `--` like this:

```
--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--
```

Is this related to the above? This is very unnerving. I've written my own "speak selection" screen reader in linux with rust and speech_dispatcher crate, works great except when I hit some character that speech-dispatcher doesn't like.

Why does speech-dispatcher stop responding with strange characters? It should just fail to speak them silently, not crash! This is really bad for us blind/low vision users, because suddenly our speech systems/screen readers stop working, which renders things inaccessible, and we basically have to stop what we're doing,

`killall -9 speech-dispatcher`

and restart our processes/whatever we're doing. Why can't this be addressed in speech-dispatcher so that it doesn't depend on every third party to clean the data being input into speech-dispatcher for gosh-knows-what combination of symbols/characters crashes it?

**Comment by sthibaul** [comment]
I have seen a comment go through asking "Why can't this be addressed in speech-dispatcher so that it doesn't depend on every third party to clean the data being input into speech-dispatcher".

We could indeed add a timeout inside speech-dispatcher, so that if a module takes a long time, we assume it is hung and just restart it, I have filed https://github.com/brailcom/speechd/issues/977
